import path from "node:path";
import type {
  DiffFile,
  FactProvenance,
  ResolvedReviewInput
} from "../types.js";
import type { InternalGitClient } from "./git-client.js";

export type DetectorFact<T> = {
  value: T;
  provenance: FactProvenance;
};

export type FileDetectionResult = {
  generated: DetectorFact<boolean>;
  vendored: DetectorFact<boolean>;
  lockfile: DetectorFact<boolean>;
  binary: DetectorFact<boolean>;
  ignored: DetectorFact<boolean>;
  submodule: DetectorFact<boolean>;
  symlink: DetectorFact<boolean>;
  language: DetectorFact<string>;
  testStatus: DetectorFact<"test" | "source" | "unknown">;
  contentReadFailed: boolean;
};

const VENDOR_SEGMENTS = new Set([
  "vendor",
  "node_modules",
  "third_party",
  "bower_components",
  ".yarn",
  "Pods"
]);

const LOCKFILE_BASENAMES = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  "Cargo.lock",
  "go.sum",
  "composer.lock",
  "Gemfile.lock",
  "poetry.lock",
  "uv.lock",
  "Pipfile.lock",
  "flake.lock",
  "gradle.lockfile",
  "packages.lock.json"
]);

const PACKAGE_MARKERS = new Set([
  "go.mod",
  "package.json",
  "Cargo.toml",
  "pyproject.toml",
  "setup.py",
  "setup.cfg",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "composer.json",
  "Gemfile",
  "mix.exs"
]);

const GENERATED_NAME_PATTERNS = [
  /\.pb\.go$/u,
  /_pb2\.py$/u,
  /\.pb\.ts$/u,
  /\.gen\.go$/u,
  /\.generated\./u,
  /\.min\.js$/u,
  /\.min\.css$/u,
  /\.snap$/u
];

const GENERATED_MARKERS = [
  /^\/\/ Code generated .* DO NOT EDIT\.$/mu,
  /@generated/u,
  /DO NOT EDIT/iu,
  /Autogenerated/iu,
  /automatically generated/iu
];

export async function detectFile(
  resolved: ResolvedReviewInput,
  file: DiffFile,
  git: InternalGitClient
): Promise<FileDetectionResult> {
  const generated = await detectGenerated(resolved, file, git);
  const language = detectLanguage(file.path);
  return {
    generated,
    vendored: detectVendored(file),
    lockfile: detectLockfile(file),
    binary: detectBinary(file),
    ignored: await detectIgnored(file, git),
    submodule: detectSubmodule(file),
    symlink: await detectSymlink(resolved, file, git),
    language,
    testStatus: detectTestStatus(file.path, language.value),
    contentReadFailed: generated.provenance.confidence === "low" && generated.provenance.source === "generated_detector"
  };
}

export function detectPackageRoot(filePath: string, treePaths: Set<string>): DetectorFact<string | undefined> {
  let current = path.posix.dirname(filePath);
  if (current === ".") {
    current = "";
  }

  for (;;) {
    for (const marker of PACKAGE_MARKERS) {
      const candidate = current.length === 0 ? marker : `${current}/${marker}`;
      if (treePaths.has(candidate)) {
        return {
          value: current.length === 0 ? "." : current,
          provenance: provenance("packageRoot", "path", "high", `nearest package marker ${candidate}`)
        };
      }
    }
    if (current.length === 0) {
      return {
        value: undefined,
        provenance: provenance("packageRoot", "path", "low", "no package marker found")
      };
    }
    const parent = path.posix.dirname(current);
    current = parent === "." ? "" : parent;
  }
}

export function detectLanguage(filePath: string): DetectorFact<string> {
  const basename = path.posix.basename(filePath);
  const lower = basename.toLowerCase();
  if (basename === "Dockerfile") {
    return detectedLanguage("dockerfile", "filename", "Dockerfile");
  }
  if (basename === "Makefile") {
    return detectedLanguage("make", "filename", "Makefile");
  }
  if (basename === "go.mod" || basename === "go.sum") {
    return detectedLanguage("go", "filename", basename);
  }

  const ext = path.posix.extname(lower);
  const map: Record<string, string> = {
    ".go": "go",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".rs": "rust",
    ".sol": "solidity",
    ".md": "markdown",
    ".py": "python",
    ".rb": "ruby",
    ".java": "java",
    ".kt": "kotlin",
    ".swift": "swift",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".sql": "sql",
    ".sh": "shell",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".toml": "toml"
  };
  const language = map[ext];
  if (language) {
    return detectedLanguage(language, "extension", ext);
  }
  return detectedLanguage("unknown", "extension", "unknown extension");
}

function detectedLanguage(
  value: string,
  source: "extension" | "filename",
  reason: string
): DetectorFact<string> {
  return {
    value,
    provenance: provenance("language", source, value === "unknown" ? "low" : "high", reason)
  };
}

function detectTestStatus(filePath: string, language: string): DetectorFact<"test" | "source" | "unknown"> {
  const basename = path.posix.basename(filePath);
  const segments = filePath.split("/");
  const isTest =
    (language === "go" && basename.endsWith("_test.go")) ||
    ((language === "typescript" || language === "javascript") &&
      (/\.(?:test|spec)\.[cm]?[jt]sx?$/u.test(basename) || segments.includes("__tests__"))) ||
    (language === "python" && (/^test_.*\.py$/u.test(basename) || /_test\.py$/u.test(basename))) ||
    (language === "rust" && segments[0] === "tests") ||
    segments.includes("test") ||
    segments.includes("tests");

  if (isTest) {
    return { value: "test", provenance: provenance("testStatus", "filename", "high", "test filename/path convention") };
  }
  if (language === "unknown") {
    return { value: "unknown", provenance: provenance("testStatus", "filename", "low", "unknown language") };
  }
  return { value: "source", provenance: provenance("testStatus", "filename", "medium", "no test convention matched") };
}

async function detectGenerated(
  resolved: ResolvedReviewInput,
  file: DiffFile,
  git: InternalGitClient
): Promise<DetectorFact<boolean>> {
  if (GENERATED_NAME_PATTERNS.some((pattern) => pattern.test(file.path))) {
    return {
      value: true,
      provenance: provenance("isGenerated", "filename", "medium", "generated filename pattern")
    };
  }

  try {
    const content = await readDetectionContent(resolved, file, git);
    if (content !== undefined && GENERATED_MARKERS.some((pattern) => pattern.test(content))) {
      return {
        value: true,
        provenance: provenance("isGenerated", "generated_detector", "high", "generated marker in reviewed revision")
      };
    }
  } catch {
    return {
      value: false,
      provenance: provenance("isGenerated", "generated_detector", "low", "reviewed revision content unavailable")
    };
  }

  return {
    value: false,
    provenance: provenance("isGenerated", "generated_detector", "high", "no generated marker found")
  };
}

function detectVendored(file: DiffFile): DetectorFact<boolean> {
  const segments = file.path.split("/");
  const matched = segments.find((segment) => VENDOR_SEGMENTS.has(segment));
  return {
    value: matched !== undefined,
    provenance: provenance(
      "isVendored",
      "path",
      matched === undefined ? "high" : "high",
      matched === undefined ? "no vendor path segment" : `vendor path segment '${matched}'`
    )
  };
}

function detectLockfile(file: DiffFile): DetectorFact<boolean> {
  const basename = path.posix.basename(file.path);
  return {
    value: LOCKFILE_BASENAMES.has(basename),
    provenance: provenance(
      "isLockfile",
      "filename",
      "high",
      LOCKFILE_BASENAMES.has(basename) ? "known lockfile basename" : "not a known lockfile basename"
    )
  };
}

function detectBinary(file: DiffFile): DetectorFact<boolean> {
  return {
    value: file.isBinary === true,
    provenance: provenance(
      "isBinary",
      "diff",
      "high",
      file.isBinary === true ? "binary diff metadata" : "no binary diff metadata"
    )
  };
}

async function detectIgnored(file: DiffFile, git: InternalGitClient): Promise<DetectorFact<boolean>> {
  const candidates = file.oldPath ? [file.path, file.oldPath] : [file.path];
  try {
    const ignored = await git.checkIgnored(candidates);
    return {
      value: candidates.some((candidate) => ignored.has(candidate)),
      provenance: provenance("isIgnored", "git", "high", "git check-ignore")
    };
  } catch {
    return {
      value: false,
      provenance: provenance("isIgnored", "git", "low", "git check-ignore unavailable")
    };
  }
}

function detectSubmodule(file: DiffFile): DetectorFact<boolean> {
  return {
    value: file.isSubmodule === true,
    provenance: provenance(
      "isSubmodule",
      "diff",
      "high",
      file.isSubmodule === true ? "gitlink/subproject diff metadata" : "no submodule diff metadata"
    )
  };
}

async function detectSymlink(
  resolved: ResolvedReviewInput,
  file: DiffFile,
  git: InternalGitClient
): Promise<DetectorFact<boolean>> {
  if (file.isSymlink === true) {
    return {
      value: true,
      provenance: provenance("isSymlink", "diff", "high", "symlink mode in diff metadata")
    };
  }
  const ref = file.status === "deleted" ? resolved.mergeBase ?? resolved.baseRef : resolved.headSha ?? resolved.headRef;
  if (!ref) {
    return {
      value: false,
      provenance: provenance("isSymlink", "git", "low", "no reviewed revision available")
    };
  }
  try {
    const entry = await git.lsTreeEntry(ref, file.status === "deleted" ? file.oldPath ?? file.path : file.path);
    return {
      value: entry?.mode === "120000",
      provenance: provenance("isSymlink", "git", entry ? "high" : "medium", "git ls-tree mode lookup")
    };
  } catch {
    return {
      value: false,
      provenance: provenance("isSymlink", "git", "low", "git ls-tree mode lookup failed")
    };
  }
}

async function readDetectionContent(
  resolved: ResolvedReviewInput,
  file: DiffFile,
  git: InternalGitClient
): Promise<string | undefined> {
  if (file.isBinary) {
    return undefined;
  }
  const ref = file.status === "deleted" ? resolved.mergeBase ?? resolved.baseRef : resolved.headSha ?? resolved.headRef;
  if (!ref) {
    return undefined;
  }
  const filePath = file.status === "deleted" ? file.oldPath ?? file.path : file.path;
  return git.catFilePrefix(ref, filePath, { maxBytes: 8192, maxLines: 64 });
}

function provenance(
  fact: string,
  source: FactProvenance["source"],
  confidence: FactProvenance["confidence"],
  reason: string
): FactProvenance {
  return { fact, source, confidence, reason };
}
