import { describe, expect, it } from "vitest";
import type { CodeninjaConfig } from "../src/types.js";
import { defaultConfig } from "../src/config/schema.js";
import { parseDiff } from "../src/git/diff-parser.js";
import { classifyChangedFiles, filterDiffFiles } from "../src/git/file-classifier.js";
import type { InternalGitClient } from "../src/git/git-client.js";
import { resolveReviewInput } from "../src/git/review-input-resolver.js";
import { commitAll, git, initRepo, nullTelemetry, writeRepoFile } from "./helpers/git.js";

describe("file filtering and classification", () => {
  it("records deterministic skip decisions and kept-file facts from detectors and path rules", async () => {
    const repo = initRepo();
    writeRepoFile(repo, "go.mod", "module example.com/repo\n");
    writeRepoFile(repo, "lib/package.json", "{\"name\":\"lib\"}\n");
    writeRepoFile(repo, "README.md", "base\n");
    commitAll(repo, "base");
    git(repo, ["checkout", "-b", "feature"]);

    writeRepoFile(repo, "src/generated.gen.go", "package src\n");
    writeRepoFile(repo, "src/marker.go", "// Code generated by tool. DO NOT EDIT.\npackage src\n");
    writeRepoFile(repo, "vendor/lib.go", "package vendor\n");
    writeRepoFile(repo, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n");
    writeRepoFile(repo, "skip/me.ts", "export const skipped = true;\n");
    writeRepoFile(repo, "src/foo_test.go", "package src\nfunc TestFoo() {}\n");
    writeRepoFile(repo, "lib/payments/a.ts", "export const amount = 1;\n");
    writeRepoFile(repo, "codeninja.toml", "[review]\ndepth = \"normal\"\n");
    commitAll(repo, "feature inventory");

    const config: CodeninjaConfig = {
      ...defaultConfig,
      classification: {
        pathRules: [
          {
            pattern: "lib/**",
            labels: ["critical"],
            reviewPriority: "critical",
            reason: "critical lib"
          },
          {
            pattern: "lib/payments/**",
            labels: ["payments"],
            processingMode: "whole-file",
            reason: "payments area"
          },
          {
            pattern: "skip/**",
            processingMode: "skip",
            reason: "not reviewable"
          }
        ]
      },
      telemetry: {
        ...defaultConfig.telemetry,
        enabled: false
      }
    };
    const resolved = await resolveReviewInput(
      { mode: "branch", branchName: "feature" },
      config,
      nullTelemetry(),
      { repoRoot: repo }
    );
    const diff = parseDiff(resolved.rawDiff);
    const { kept, decisions } = await filterDiffFiles(resolved, diff, config, nullTelemetry());
    const facts = await classifyChangedFiles(resolved, kept, decisions, config, nullTelemetry());

    expect(decisions).toHaveLength(diff.files.length);
    expect(decisions).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ path: "src/generated.gen.go", action: "skip", reason: "generated file" }),
        expect.objectContaining({ path: "src/marker.go", action: "skip", reason: "generated file" }),
        expect.objectContaining({ path: "vendor/lib.go", action: "skip", reason: "vendored/dependency file" }),
        expect.objectContaining({ path: "pnpm-lock.yaml", action: "skip", reason: "lockfile" }),
        expect.objectContaining({ path: "skip/me.ts", action: "skip", reason: "configured skip rule" })
      ])
    );
    expect(kept.map((file) => file.path).sort()).toEqual([
      "codeninja.toml",
      "lib/payments/a.ts",
      "src/foo_test.go"
    ]);

    const payment = facts.find((fact) => fact.path === "lib/payments/a.ts");
    expect(payment).toMatchObject({
      language: "typescript",
      packageRoot: "lib",
      processingMode: "whole-file",
      reviewPriority: "critical",
      labels: ["critical", "payments"],
      testStatus: "source"
    });

    const testFile = facts.find((fact) => fact.path === "src/foo_test.go");
    expect(testFile).toMatchObject({
      language: "go",
      processingMode: "whole-file",
      testStatus: "test"
    });

    const policy = facts.find((fact) => fact.path === "codeninja.toml");
    expect(policy?.labels).toContain("policy-change");
    expect(facts.every((fact) => fact.processingMode !== "skip")).toBe(true);
  });

  it("skips committed files that match gitignore rules", async () => {
    const repo = initRepo();
    writeRepoFile(repo, ".gitignore", "ignored-artifact.txt\n");
    writeRepoFile(repo, "README.md", "base\n");
    commitAll(repo, "base");
    git(repo, ["checkout", "-b", "feature"]);
    writeRepoFile(repo, "ignored-artifact.txt", "force-added ignored artifact\n");
    git(repo, ["add", "-f", "ignored-artifact.txt"]);
    git(repo, ["commit", "-m", "force add ignored artifact"]);

    const resolved = await resolveReviewInput(
      { mode: "branch", branchName: "feature" },
      defaultConfig,
      nullTelemetry(),
      { repoRoot: repo }
    );
    const diff = parseDiff(resolved.rawDiff);
    const { kept, decisions } = await filterDiffFiles(resolved, diff, defaultConfig, nullTelemetry());

    expect(diff.files.map((file) => file.path)).toEqual(["ignored-artifact.txt"]);
    expect(kept).toEqual([]);
    expect(decisions).toEqual([
      expect.objectContaining({
        path: "ignored-artifact.txt",
        action: "skip",
        reason: "ignored path"
      })
    ]);
  });

  it("uses capped revision reads for generated-marker detection", async () => {
    let prefixRead = false;
    const gitClient: InternalGitClient = {
      revParse: async () => "head",
      catFile: async () => {
        throw new Error("full catFile should not be used by detectors");
      },
      catFilePrefix: async () => {
        prefixRead = true;
        return "// Code generated by tool. DO NOT EDIT.\npackage src\n";
      },
      lsTree: async () => [],
      lsFiles: async () => [],
      grep: async () => [],
      mergeBase: async () => "base",
      log: async () => [],
      diff: async () => "",
      fetch: async () => undefined,
      isShallow: async () => false,
      currentBranch: async () => "feature",
      isInsideWorktree: async () => true,
      repoRoot: async () => "/tmp/repo",
      commitExists: async () => true,
      resolveBranch: async () => undefined,
      remotes: async () => [],
      fetchFrom: async () => undefined,
      deleteRef: async () => undefined,
      listRefs: async () => [],
      lsTreeEntry: async () => undefined,
      emptyTreeSha: async () => "empty",
      firstParent: async () => "base",
      parentShas: async () => ["base"],
      checkIgnored: async () => new Set()
    };

    const { decisions } = await filterDiffFiles(
      {
        mode: "branch",
        repoRoot: "/tmp/repo",
        baseRef: "base",
        headRef: "head",
        mergeBase: "base",
        headSha: "head",
        commits: [],
        rawDiff: ""
      },
      {
        files: [
          {
            path: "src/generated.go",
            status: "modified",
            language: "go",
            hunks: []
          }
        ]
      },
      defaultConfig,
      nullTelemetry(),
      { git: gitClient }
    );

    expect(prefixRead).toBe(true);
    expect(decisions).toEqual([
      expect.objectContaining({ path: "src/generated.go", action: "skip", reason: "generated file" })
    ]);
  });
});
